### PR TITLE
Add e2e tests for in-place upgrades

### PR DESCRIPTION
**Pull request by sachinkumarsingh092**
### Summary

Added e2e tests for `inPlace` upgrades.  Also did some refactoring to make it easy if and when we want different tests for different upgrade strategies.

### CODE REVIEW

**Comment by ktsakalozos** [comment]
Thank you for this work @sachinkumarsingh092 . These e2e tests are run during a release, therefore we want to have both upgrade strategies to be checked. I saw you have introduced a env variable through which we can select the upgrade strategy. Could have a separate test to upgrade a non-HA cluster? Maybe a subtest test could work.

**Review by ktsakalozos — CHANGES_REQUESTED** [review]
Please see comments

**Comment by sachinkumarsingh092** [comment]
Yeah, making a new subtest is very easy now with all the refactoring. I thought about making a new test for in-place and having 2 tests for Rollout and in-place separately. But after having already executed one of the tests, say rollout upgrades, the cluster is now in a new version. Unless we are sure that an even newer version exists, this can break the in-place upgrade tests. We have these options to now test in-place upgrades:
1. Downgrade the cluster to the previous version before in-place tests.
2. Make a new cluster entirely with the older version before in-place tests.
3. Hardcode the versions for the 3 consecutive available versions. Ex 1.24 -> 1.25 (rollouts) then 1.25 -> 1.26 (in-place).

WDYT?

**Comment by ktsakalozos** [comment]
LGTM +1

**Pull request merged**
